# Site Specific Configuration
name: Pawel's Blog
description: On books, code and random thoughts
url: https://www.pawelrusin.com
author: pauchan
# timezone: America/Toronto
# timezone_short: ET

# Keywords
keywords: ['pawel', 'rusin', 'books', 'code']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Exclusions
exclude: 
  - 'README.md'
  - 'COPYING'
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

